function test_axes_and_fft_helpers()
%TEST_AXES_AND_FFT_HELPERS 定向回归坐标轴与基础 FFT 时频实现。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(fullfile(projectRoot, 'functions')));

cfg = struct( ...
    'fmcw_startfreq', 76.3, ...
    'fmcw_bandwidth', 300, ...
    'fmcw_chirp_rampup', 43, ...
    'fmcw_chirp_period', 48, ...
    'adc_freq', 25, ...
    'dec_factor', 1, ...
    'rng_nfft', 8, ...
    'vel_nfft', 5, ...
    'nchirp', 5, ...
    'tx_groups', uint32([1 0 0 0]));

axesInfo = derive_measured_axes(cfg, 8, 5);
assert(strcmp(axesInfo.tx_mode, 'SISO'));
assert(axesInfo.velocity_axis_mps(3) == 0);

cfg.tx_groups = uint32([1 1 0 0]);
try
    derive_measured_axes(cfg, 8, 5);
    error('test_axes_and_fft_helpers:ExpectedFailure', ...
        'Simultaneous unresolved TX mode should be rejected.');
catch err
    assert(strcmp(err.identifier, ...
        'derive_measured_axes:UnsupportedTxMode'));
end

simCfg = struct('c', 1, 'sample_rate', 1, 'slope', 1, ...
    'chirp_period', 2, 'lambda', 4);
oddResult = process_simulated_range_doppler(zeros(8, 5), simCfg);
evenResult = process_simulated_range_doppler(zeros(8, 6), simCfg);
assert(max(abs( ...
    oddResult.velocity_axis_mps - [-0.4 -0.2 0 0.2 0.4])) < 1e-12);
assert(max(abs( ...
    evenResult.velocity_axis_mps - [-0.5 -1/3 -1/6 0 1/6 1/3])) < 1e-12);

tone = exp(1j * 2*pi*(0:15)'/8);
[powerDb, timeAxisS, frequencyAxisHz] = ...
    compute_fft_spectrogram(tone, 8, 4, 8, 8);
assert(isequal(size(powerDb), [8 3]));
assert(isequal(frequencyAxisHz, (-4:3).'));
assert(max(abs(timeAxisS - [3.5 7.5 11.5]/8)) < 1e-12);
assert(abs(max(powerDb(:))) < 1e-12);

fprintf('Axes and base-FFT helper checks passed.\n');

end
