clear;
clc;
close all;

%% ============================================================
% CTSAI-A100 Issue #8
% Indoor / Outdoor representative measured-data analysis
%
% Repository representative samples:
%
%   indoor_case_01/run_001_Pf0_Rx0.txt
%   indoor_case_02/run_001_Pf0_Rx0.txt
%   indoor_case_03/run_001_Pf0_Rx0.txt
%   outdoor_case_01/run_001_Pf0_Rx0.txt
%
% Processing:
%
%   ADC
%    -> Range FFT
%    -> Range-Doppler / 2D FFT
%    -> MTI2
%
%% ============================================================

%% Locate project

thisFile = mfilename('fullpath');
testDir = fileparts(thisFile);
projectRoot = fileparts(testDir);

addpath(genpath(fullfile(projectRoot, 'functions')));

dataRoot = fullfile( ...
    projectRoot, ...
    'data', ...
    'measured');

resultRoot = fullfile( ...
    projectRoot, ...
    'results', ...
    'measured');

%% Radar configuration

configFile = fullfile( ...
    projectRoot, ...
    'config', ...
    'sensor_config_init0.hxx');

cfg = load_ctsaia100_config(configFile);

%% Processing options

ioOpts.allow_zero_pad = false;

dynamicRangeDb = 60;

%% Four representative scenes

sceneNames = {
    'indoor_case_01'
    'indoor_case_02'
    'indoor_case_03'
    'outdoor_case_01'
};

fileName = 'run_001_Pf0_Rx0.txt';

fprintf('\n');
fprintf('=====================================================\n');
fprintf(' CTSAI-A100 Issue #8 Indoor / Outdoor Analysis\n');
fprintf('=====================================================\n\n');

%% Process scenes

for iScene = 1:numel(sceneNames)

    sceneName = sceneNames{iScene};

    fprintf('-----------------------------------------------------\n');
    fprintf('Processing scene: %s\n', sceneName);
    fprintf('-----------------------------------------------------\n');

    filePath = fullfile( ...
        dataRoot, ...
        sceneName, ...
        fileName);

    if ~isfile(filePath)
        error('ADC file not found: %s', filePath);
    end

    outputDir = fullfile( ...
        resultRoot, ...
        sceneName);

    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end

    %% ---------------------------------------------------------
    % 1. Read ADC TXT
    %% ---------------------------------------------------------

    [packedWords, header, trailer] = ...
        read_adc_txt(filePath, ioOpts);

    fprintf('RX index          : %d\n', ...
        header.rx_index);

    fprintf('Samples per chirp : %d\n', ...
        header.samples_per_chirp);

    fprintf('Chirp count       : %d\n', ...
        header.chirp_count);

    fprintf('Trailer values    : %d\n', ...
        numel(trailer));

    %% ---------------------------------------------------------
    % 2. Unpack ADC
    %% ---------------------------------------------------------

    adc = unpack_uint32_adc( ...
        packedWords, ...
        header.samples_per_chirp, ...
        header.chirp_count);

    adc = double(adc);

    numSamples = size(adc, 1);
    numChirps  = size(adc, 2);

    fprintf('ADC matrix        : %d x %d\n', ...
        numSamples, ...
        numChirps);

    %% ---------------------------------------------------------
    % 3. Physical axes
    %% ---------------------------------------------------------

    axesInfo = derive_measured_axes( ...
        cfg, ...
        numSamples, ...
        numChirps);

    rangeAxisM = ...
        axesInfo.range_axis_m;

    velocityAxisMps = ...
        axesInfo.velocity_axis_mps;

    numRangeBins = ...
        numel(rangeAxisM);

    fprintf('Range resolution  : %.4f m/bin\n', ...
        axesInfo.range_resolution_m);

    fprintf('Velocity resolution: %.4f m/s/bin\n', ...
        axesInfo.velocity_resolution_mps);

    %% ---------------------------------------------------------
    % 4. Remove fast-time DC
    %% ---------------------------------------------------------

    adcProcessed = ...
        adc - mean(adc, 1);

    %% ---------------------------------------------------------
    % 5. Range FFT
    %% ---------------------------------------------------------

    rangeWindow = ...
        make_window('hann', numSamples);

    adcWindowed = ...
        adcProcessed .* ...
        repmat(rangeWindow, 1, numChirps);

    rangeFftFull = ...
        fft(adcWindowed, numSamples, 1);

    rangeCube = ...
        rangeFftFull(1:numRangeBins, :);

    %% ---------------------------------------------------------
    % 6. Range spectrum
    %% ---------------------------------------------------------

    rangePower = ...
        mean(abs(rangeCube).^2, 2);

    rangePowerDb = ...
        10 * log10( ...
            (rangePower + eps) / ...
            (max(rangePower) + eps));

    fig = figure( ...
        'Name', ...
        [sceneName ' Range Spectrum']);

    plot( ...
        rangeAxisM, ...
        rangePowerDb, ...
        'LineWidth', ...
        1.2);

    grid on;

    xlabel('Range (m)');
    ylabel('Normalized Power (dB)');

    title(sprintf( ...
        '%s - Range Spectrum', ...
        strrep(sceneName, '_', ' ')));

    ylim([-dynamicRangeDb 0]);

    saveas( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            'range_spectrum.png'));

    close(fig);

    %% ---------------------------------------------------------
    % 7. Range-Doppler BEFORE MTI
    %% ---------------------------------------------------------

    dopplerWindow = ...
        make_window('hann', numChirps).';

    rangeWindowed = ...
        rangeCube .* ...
        repmat( ...
            dopplerWindow, ...
            numRangeBins, ...
            1);

    rdBefore = ...
        fftshift( ...
            fft( ...
                rangeWindowed, ...
                numChirps, ...
                2), ...
            2);

    rdBeforePower = ...
        abs(rdBefore).^2;

    %% ---------------------------------------------------------
    % 8. MTI2
    %% ---------------------------------------------------------

    rangeCube3D = reshape( ...
        rangeCube, ...
        numRangeBins, ...
        numChirps, ...
        1);

    clutterOpts = struct();

    clutterOpts.method = 'MTI2';
    clutterOpts.normalize_output_power = false;

    [rangeMti2, ~] = ...
        suppress_clutter( ...
            rangeCube3D, ...
            clutterOpts);

    rangeMti2 = reshape( ...
        rangeMti2, ...
        numRangeBins, ...
        numChirps);

    rangeMti2Windowed = ...
        rangeMti2 .* ...
        repmat( ...
            dopplerWindow, ...
            numRangeBins, ...
            1);

    rdMti2 = ...
        fftshift( ...
            fft( ...
                rangeMti2Windowed, ...
                numChirps, ...
                2), ...
            2);

    rdMti2Power = ...
        abs(rdMti2).^2;

    %% ---------------------------------------------------------
    % 9. Shared power reference
    %
    % Important:
    % Before / After MTI must use the same reference power.
    %% ---------------------------------------------------------

    sharedReference = ...
        max([ ...
            rdBeforePower(:); ...
            rdMti2Power(:)]);

    rdBeforeDb = ...
        10 * log10( ...
            (rdBeforePower + eps) / ...
            (sharedReference + eps));

    rdMti2Db = ...
        10 * log10( ...
            (rdMti2Power + eps) / ...
            (sharedReference + eps));

    %% ---------------------------------------------------------
    % 10. Plot BEFORE MTI
    %% ---------------------------------------------------------

    fig = figure( ...
        'Name', ...
        [sceneName ' RD Before MTI']);

    imagesc( ...
        velocityAxisMps, ...
        rangeAxisM, ...
        rdBeforeDb);

    axis xy;

    xlabel('Radial Velocity (m/s)');
    ylabel('Range (m)');

    title(sprintf( ...
        '%s - Range-Doppler Before MTI', ...
        strrep(sceneName, '_', ' ')));

    colorbar;

    caxis([-dynamicRangeDb 0]);

    saveas( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            'range_doppler_before_mti.png'));

    close(fig);

    %% ---------------------------------------------------------
    % 11. Plot AFTER MTI2
    %% ---------------------------------------------------------

    fig = figure( ...
        'Name', ...
        [sceneName ' RD After MTI2']);

    imagesc( ...
        velocityAxisMps, ...
        rangeAxisM, ...
        rdMti2Db);

    axis xy;

    xlabel('Radial Velocity (m/s)');
    ylabel('Range (m)');

    title(sprintf( ...
        '%s - Range-Doppler After MTI2', ...
        strrep(sceneName, '_', ' ')));

    colorbar;

    caxis([-dynamicRangeDb 0]);

    saveas( ...
        fig, ...
        fullfile( ...
            outputDir, ...
            'range_doppler_after_mti2.png'));

    close(fig);

    fprintf('Finished: %s\n\n', sceneName);

end

fprintf('=====================================================\n');
fprintf(' All four representative scenes completed.\n');
fprintf('=====================================================\n\n');