function print_profile_summary(cfg)
%PRINT_PROFILE_SUMMARY Print waveform, MIMO and physical parameters.
fprintf('Configuration: %s\n', cfg.source_file);
fprintf('  Carrier: %.3f GHz, bandwidth: %.1f MHz\n', ...
    cfg.fmcw_startfreq, cfg.fmcw_bandwidth);
fprintf('  MIMO mode: %s, chirp groups: %d, active physical TX: %s, RX: %d\n', ...
    cfg.mimo.mode, cfg.mimo.group_count, ...
    mat2str(cfg.mimo.active_tx_indices), cfg.num_rx);
fprintf('  Raw chirps: %d, slow-time chirps/group: %d, virtual channels: %d\n', ...
    cfg.nchirp, cfg.slow_time_chirp_num, cfg.nvirtual_array);
fprintf('  Virtual antenna source indices: %s\n', ...
    mat2str(cfg.virtual_array.source_antenna_index.'));
if cfg.mimo.ddma_ready
    fprintf('  DDMA definition: %s\n', cfg.mimo.ddma_definition_source);
    fprintf('  DDMA phase steps (active TX): %s deg/chirp\n', ...
        mat2str(cfg.mimo.ddma_phase_step_deg_by_tx( ...
        cfg.mimo.active_tx_indices)));
end
fprintf('  Range FFT: %d, Doppler FFT: %d\n', cfg.rng_nfft, cfg.vel_nfft);
fprintf('  Range bin: %.4f m, max plotted range: %.2f m\n', ...
    cfg.range_resolution_m, cfg.max_range_m);
fprintf('  Velocity bin: %.4f m/s, unambiguous limit: +/-%.2f m/s\n', ...
    cfg.velocity_resolution_mps, cfg.max_unambiguous_velocity_mps);
end
